### Test checkDeviceId Endpoint with valid deviceId
POST http://localhost:8080/api/v1/test
Content-Type: application/json

{
  "deviceId": "validDeviceId123"
}

### Test checkDeviceId Endpoint with blank deviceId
POST http://localhost:8080/api/v1/test
Content-Type: application/json

{
  "deviceId": ""
}

### Health Check
GET http://localhost:8080/api/v1/test


### GET Widget Info
GET http://localhost:8080/api/v1/{{deviceId}}
Content-Type: application/json
# run with enviroment(dev)
