-- Clothes Table Creation
create table clothes
(
    created_at       timestamp(6),
    id               bigint generated by default as identity
        primary key,
    updated_at       timestamp(6),
    category         varchar(255)
        constraint clothes_category_check
            check ((category)::text = ANY
        ((ARRAY ['SLEEVELESS'::character varying, 'SHORT_SLEEVE'::character varying, 'LONG_SLEEVE'::character varying, 'SHORT_PANTS'::character varying, 'LONG_PANTS'::character varying, 'SHOES'::character varying, 'OUTWEAR'::character varying, 'ACCESSORY'::character varying])::text[])),
    cloth_image_url  varchar(255),
    product_page_url varchar(255),
    site             varchar(255)
        constraint clothes_site_check
            check ((site)::text = ANY
                   ((ARRAY ['MUSINSA'::character varying, 'ABLY'::character varying, 'ZIGZAG'::character varying, 'ETC'::character varying])::text[]))
);


-- Users Table Creation
create table users
(
    created_at timestamp(6),
    id         bigint generated by default as identity
        primary key,
    updated_at timestamp(6),
    device_id  varchar(255) not null
        unique
);


-- Fitting Models Table Creation
create table fitting_models
(
    created_at      timestamp(6),
    id              bigint generated by default as identity
        primary key,
    updated_at      timestamp(6),
    user_id         bigint       not null
        constraint fkc7v1ht4vuv36iqkghffcefijp
            references users,
    model_image_url varchar(255) not null
);


-- Fittings Table Creation
create table fittings
(
    cloth_id         bigint       not null
        unique
        constraint fk70cmqik6u8nii5f0t2o7a4csh
            references clothes,
    created_at       timestamp(6),
    id               bigint generated by default as identity
        primary key,
    updated_at       timestamp(6),
    user_id          bigint       not null
        constraint fk4h741hu4mf9vwctw3hk3k7nwy
            references users,
    llm_advice       text,
    result_image_url varchar(255) not null
);
