create table clothes
(
    created_at       timestamp(6),
    id               bigint generated by default as identity
        primary key,
    updated_at       timestamp(6),
    category         varchar(255) not null
        constraint clothes_category_check
            check ((category)::text = ANY
        ((ARRAY ['ACCESSORY'::character varying, 'LONG_PANTS'::character varying, 'LONG_SLEEVE'::character varying, 'OUTWEAR'::character varying, 'SHOES'::character varying, 'SHORT_PANTS'::character varying, 'SHORT_SLEEVE'::character varying, 'SLEEVELESS'::character varying])::text[])),
    cloth_image_url  varchar(255) not null,
    product_page_url varchar(255),
    site             varchar(255)
        constraint clothes_site_check
            check ((site)::text = ANY
                   ((ARRAY ['MUSINSA'::character varying, 'ABLY'::character varying, 'ZIGZAG'::character varying, 'ETC'::character varying])::text[]))
);

alter table clothes
    owner to "8fit-dev";

create table users
(
    created_at timestamp(6),
    id         bigint generated by default as identity
        primary key,
    updated_at timestamp(6),
    device_id  varchar(255) not null
        unique
);

alter table users
    owner to "8fit-dev";

create table fitting_models
(
    created_at      timestamp(6),
    id              bigint generated by default as identity
        primary key,
    updated_at      timestamp(6),
    user_id         bigint       not null
        constraint fkc7v1ht4vuv36iqkghffcefijp
            references users,
    model_image_url varchar(255) not null
);

alter table fitting_models
    owner to "8fit-dev";

create table fittings
(
    cloth_id         bigint       not null
        unique
        constraint fk70cmqik6u8nii5f0t2o7a4csh
            references clothes,
    created_at       timestamp(6),
    fitting_model_id bigint       not null
        constraint fkkh9ss4k4ietvkpmus8ehdcyp4
            references fitting_models,
    id               bigint generated by default as identity
        primary key,
    updated_at       timestamp(6),
    llm_advice       text,
    result_image_url varchar(255) not null
);

alter table fittings
    owner to "8fit-dev";



-- Insert mock data
-- Insert users
insert into users (created_at, updated_at, device_id) values
('2024-11-01 10:00:00', '2024-11-01 10:00:00', 'validDeviceId123');

-- Insert clothes
insert into clothes (created_at, updated_at, category, cloth_image_url, product_page_url, site) values
('2024-11-06 01:33:53.853651', '2024-11-06 01:33:53.853651', 'SHORT_SLEEVE', 'https://8fit-bucket.s3.ap-northeast-2.amazonaws.com/341b53c4-551f-49ca-b4f6-672aa142770a_mockCloth2.jpg', null, 'MUSINSA'),
('2024-11-06 01:34:00.123456', '2024-11-06 01:34:00.123456', 'LONG_PANTS', 'https://8fit-bucket.s3.ap-northeast-2.amazonaws.com/341b53c4-551f-49ca-b4f6-672aa142770a_mockCloth2.jpg', null, 'ZIGZAG');

-- Insert fitting models
insert into fitting_models (created_at, updated_at, user_id, model_image_url) values
('2024-11-06 01:30:00.000000', '2024-11-06 01:30:00.000000', 1, 'https://8fit-bucket.s3.ap-northeast-2.amazonaws.com/a0161c06-cffa-42e7-b44f-bb4066c3570c.png'),
('2024-11-06 01:31:00.000000', '2024-11-06 01:31:00.000000', 1, 'https://8fit-bucket.s3.ap-northeast-2.amazonaws.com/a0161c06-cffa-42e7-b44f-bb4066c3570c.png');

-- Insert fittings
insert into fittings (created_at, updated_at, fitting_model_id, cloth_id, result_image_url, llm_advice) values
('2024-11-06 01:35:00.111111', '2024-11-06 01:35:00.111111', 1, 1, 'https://8fit-bucket.s3.ap-northeast-2.amazonaws.com/32422ad6-0b8a-4f71-8075-5728b8286a14.png', 'Advice 1'),
('2024-11-06 01:36:00.222222', '2024-11-06 01:36:00.222222', 1, 2, 'https://8fit-bucket.s3.ap-northeast-2.amazonaws.com/32422ad6-0b8a-4f71-8075-5728b8286a14.png', 'Advice 2');
