server:
  servlet:
    context-path: /api/v1

spring:
  application:
    name: web-application-server

  config:
    import: optional:file:.env[.properties]
    activate:
      on-profile: prod

  servlet:
    # file upload
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgresdb:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        format_sql: true
        use_sql_comments: true

  # aws
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ${AWS_REGION}
      s3:
        bucket: ${AWS_S3_BUCKET_NAME}

# logging
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm.jdbc.bind: TRACE

# Swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html




